bankproject/bankapp/urls.py
from . import views
from django.urls import path
app_name='bankapp'
urlpatterns = [
    path('',views.home,name='home'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('biodata/',views.register,name='biodata'),
    ]

bankproject/bankproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [

    path('',include('bankapp.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bankproject/bankapp/models.py
from django.db import models



# Create your models here.

class Member(models.Model):


    username1 = models.CharField(max_length=30)
    password1 = models.CharField(max_length=12)

    def __str__(self):
        return self.username1

bankproject/bankapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect




def home(request):

    return render(request,"base.html")
def login(request):
    if request.method == 'POST':
        username1 = request.POST['username']
        password1 = request.POST['password']
        user = auth.authenticate(username=username1,password=password1)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"invalid Username or Password")
            return redirect('login')
    return render(request,"login.html")


def register(request):
    if request.method=='POST':
        user = request.POST['username']
        password = request.POST['password']
        cnpassword = request.POST['password1']
        if password == cnpassword:
            if User.objects.filter(username=user).exists():
                messages.info(request, "username taken")
                return redirect('register')

            else:
                newvar = User.objects.create_user(username=user, password=password)

                newvar.save()
                return redirect('login')
        else:
            messages.info(request, "password not matching")
            return redirect('register')
        return redirect('/')

    return render(request, "register.html")
def biodata(request):

    return render(request,'biodata.html')

bankproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheets" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription%}{%endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <style>

    form{ background-color:aqua; width:8cm; padding:20px;border-radius:10px;}
    h1{ color:red;}
</style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
<div>

{% include 'navbar.html' %}
{% block content %}
{% endblock %}

</div>
</body>
</html>

bankproject/templates/biodata.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheets" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription%}{%endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <style>


    form{ background-color:aqua; width:30%; padding:20px;border-radius:10px;}
    h1{ color:red;}
</style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>




<form method="POST">
{% csrf_token %}
<label for="name">Name:</label>
<input type="text" name="name" id="name">
<br/>
<label for="age">Age:</label>
<input type="number" name="age" id="age">
<br/>
<label for="gender">Gender:</label>
<select name="gender" id="gender">
<option value="" selected>-- Select --</option>
    <option value="Male">Male</option>
<option value="Female">Female</option>
<option value="Other">Other</option>
</select>
<br/>
<label for="dob">Date of Birth: </label>
<input type = "date" name = "dob" id = "dob">
    <br>
    <label for="district">District:</label>
<select name="district" id="district">
<option value="" selected>Select</option>
    <option value="d1">Thiruvananthapuram</option>
<option value="d2">Kollam</option>
<option value="d3">Pathanamthitta</option>
     <option value="d4">Alappuzha</option>
<option value="d5">Kottayam</option>
<option value="d6">Idukki</option>
     <option value="d7">Eranakulam</option>
<option value="d8">Thrissur</option>
<option value="d9">Paalakkad</option>
     <option value="d10">Malappuram</option>
<option value="d11">Kozhikkode</option>
<option value="d12">Wayanad</option>
    <option value="d13">Kannur</option>
<option value="d14">Kasargod</option>
</select>
    <br/>
    <label for="dob">Account type: </label>
<div class="form-check">
  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
  <label class="form-check-label" for="flexRadioDefault1">
    Current
  </label>
</div>
<div class="form-check">
  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
  <label class="form-check-label" for="flexRadioDefault2">
 Savings
  </label>
</div>
    <div class="form-check">
  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault3" checked>
  <label class="form-check-label" for="flexRadioDefault2">
 Fixed Deposit
  </label>
</div>
    <div class="form-check">
  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault4" checked>
  <label class="form-check-label" for="flexRadioDefault2">
 Salary
  </label>
</div>

<br/>
<label for = "email">Email: </label>
    <input type = "email" name = "email" id = "email">

<br/>
    <label for = "contactno">Contact Number: </label>

 <input type = "tel" name = "contactno" id = "contactno">
     <br />
     <input type = "submit" value=Submit />
  </form>

bankproject/templates/login.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheets" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription%}{%endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <style>


    form{ background-color:aqua; width:30%; padding:20px;border-radius:10px;}
    h1{ color:red;}
</style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>


<h1>LOGIN</h1>
<form action="login" method="POST">
    {% csrf_token %}
    <input type="text" name="username"  placeholder="enter your username"><br><br>

    <input type="password" name="password" placeholder="enter your password"><br><br>

    <a class="button btn btn-secondary" href="{% url 'bankapp:biodata' %}">Submit</a>
    <a href="{% url 'bankapp:register' %}">Click here to Register</a>
</form>
{% endblock %}

bankproject/templates/navbar.html
{% load static %}
<style type="text/css">
nav{
width:100%
height:80px;
background-color:white;

}
nav ul{
float:left;
}
ul li{
list-style-type:none;
display:inline-block;
padding:10px;
}
ul li a{
text-decoration:none;
font-size:18px;
padding:12px;
color:#fff;
}
</style>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <p class="navbar-brand">Welcome to Obsidian Bank</p>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'bankapp:login' %}"><b>Login</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bankapp:register' %}"><b>Register</b></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <b>Branches</b>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        
      </ul>

    </div>
  </div>
</nav>
<img src="{% static 'img/banner.png' %}" alt="logoimg" style="width:100%;height:530px;">

bankproject/templates/register.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheets" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription%}{%endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <style>


    form{ background-color:aqua; width:30%; padding:20px;border-radius:10px;}
    h1{ color:red;}
</style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>


<h1>REGISTRATION</h1>
<form action="register" method="POST">
    {% csrf_token %}
   <div class="mb-3">
       <div class="container-fluid">
      <label for="formGroupExampleInput" class="form-label">Username</label>
      <input type="text" class="form-control" name="username" id="formGroupExampleInput" placeholder="username"><br><br>
   </div>
   <div class="mb-3">
        <label for="formGroupExampleInput2" class="form-label">Password</label>
        <input type="password" class="form-control"  name="password" id="formGroupExampleInput2" placeholder="Enter your password"><br><br>
       <div>
           <label for="formGroupExampleInput2" class="form-label">Confirm Password</label>
           <input type="password" class="form-control" name="password1" id="formGroupExampleInput3" placeholder="Re Enter password"><br><br>
       </div>
  </div>

    <a class="button btn btn-primary" href="{% url 'bankapp:login' %}" type="submit">Submit</a>
    <a class="button btn btn-primary" href="{% url 'bankapp:home' %}">Confirm</a>
    </div>
</form>
</html>
{% endblock %}